import { ComplexityUnit } from "@/types/apiDataInterface";

export const MOCK_COMPLEXITY_DATA: ComplexityUnit[] = [
  {
    id: "fn-1",
    kind: "functions",
    name: "getUserData",
    startLine: 1,
    endLine: 20,
    text: "function getUserData() { /* API call */ }",
    timeComplexity: { notation: "O(n)", confidence: 30, flags: [] },
    spaceComplexity: { notation: "O(1)", confidence: 30, flags: [] },
    timeScore: 30,
    spaceScore: 10,
    totalScore: 40,
    riskLevel: "LOW",
    confidence: 0.92,
    reasons: [
    ],
    matchedKeywords: ["loop"],
    tierUsed: "free",
  },
  {
    id: "fn-2",
    kind: "functions",
    name: "processTransactions",
    startLine: 10,
    endLine: 60,
    text: "function processTransactions() { /* heavy loop */ }",
    timeComplexity: { notation: "O(n^2)", confidence: 30, flags: [] },
    spaceComplexity: { notation: "O(n)", confidence: 30, flags: [] },
    timeScore: 70,
    spaceScore: 40,
    totalScore: 110,
    riskLevel: "HIGH",
    confidence: 0.88,
    reasons: [
    ],
    matchedKeywords: ["nested-loop"],
    tierUsed: "free",
  },
  {
    id: "fn-3",
    kind: "functions",
    name: "calculateMetrics",
    startLine: 5,
    endLine: 35,
    text: "function calculateMetrics() {}",
    timeComplexity: { notation: "O(n log n)", confidence: 30, flags: [] },
    spaceComplexity: { notation: "O(n)", confidence: 30, flags: [] },
    timeScore: 50,
    spaceScore: 30,
    totalScore: 80,
    riskLevel: "MEDIUM",
    confidence: 0.85,
    reasons: [],
    matchedKeywords: ["sort"],
    tierUsed: "free",
  },
  {
    id: "fn-4",
    kind: "functions",
    name: "renderUI",
    startLine: 2,
    endLine: 15,
    text: "function renderUI() {}",
    timeComplexity: { notation: "O(1)", confidence: 30, flags: [] },
    spaceComplexity: { notation: "O(1)", confidence: 30, flags: [] },
    timeScore: 5,
    spaceScore: 5,
    totalScore: 10,
    riskLevel: "LOW",
    confidence: 0.95,
    reasons: [],
    matchedKeywords: [],
    tierUsed: "free",
  },
  {
    id: "fn-5",
    kind: "functions",
    name: "parseData",
    startLine: 12,
    endLine: 45,
    text: "function parseData() {}",
    timeComplexity: { notation: "O(n)", confidence: 30, flags: [] },
    spaceComplexity: { notation: "O(n)", confidence: 30, flags: [] },
    timeScore: 40,
    spaceScore: 35,
    totalScore: 75,
    riskLevel: "MEDIUM",
    confidence: 0.87,
    reasons: [
    ],
    matchedKeywords: ["array"],
    tierUsed: "free",
  },
  {
    id: "fn-6",
    kind: "functions",
    name: "optimizeSearch",
    startLine: 3,
    endLine: 50,
    text: "function optimizeSearch() {}",
    timeComplexity: { notation: "O(log n)", confidence: 30, flags: [] },
    spaceComplexity: { notation: "O(1)", confidence: 30, flags: [] },
    timeScore: 20,
    spaceScore: 10,
    totalScore: 30,
    riskLevel: "LOW",
    confidence: 0.91,
    reasons: [],
    matchedKeywords: ["binary-search"],
    tierUsed: "free",
  },
  {
    id: "fn-7",
    kind: "functions",
    name: "handleRequests",
    startLine: 6,
    endLine: 80,
    text: "function handleRequests() {}",
    timeComplexity: { notation: "O(n^2)", confidence: 30, flags: [] },
    spaceComplexity: { notation: "O(n)", confidence: 30, flags: [] },
    timeScore: 80,
    spaceScore: 40,
    totalScore: 120,
    riskLevel: "CRITICAL",
    confidence: 0.83,
    reasons: [

    ],
    matchedKeywords: ["nested-loop"],
    tierUsed: "free",
  },
  {
    id: "fn-8",
    kind: "functions",
    name: "cacheResult",
    startLine: 1,
    endLine: 10,
    text: "function cacheResult() {}",
    timeComplexity: { notation: "O(1)", confidence: 30, flags: [] },
    spaceComplexity: { notation: "O(n)", confidence: 30, flags: [] },
    timeScore: 5,
    spaceScore: 20,
    totalScore: 25,
    riskLevel: "LOW",
    confidence: 0.94,
    reasons: [],
    matchedKeywords: ["cache"],
    tierUsed: "free",
  },
  {
    id: "fn-9",
    kind: "functions",
    name: "validateInput",
    startLine: 4,
    endLine: 18,
    text: "function validateInput() {}",
    timeComplexity: { notation: "O(n)", confidence: 30, flags: [] },
    spaceComplexity: { notation: "O(1)", confidence: 30, flags: [] },
    timeScore: 25,
    spaceScore: 10,
    totalScore: 35,
    riskLevel: "LOW",
    confidence: 0.93,
    reasons: [],
    matchedKeywords: ["validation"],
    tierUsed: "free",
  },
]