import type { MethodPreview } from "../types/fileUploadInterface";

export const MOCK_METHOD_COMPLEXITY: MethodPreview[] = [
  {
    id: "constantOperation:13",
    kind: "method",
    name: "constantOperation",
    startLine: 13,
    endLine: 15,
    text: "constantOperation(): number { return 1 + 1; }",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    timeScore: 5,
    spaceScore: 5,
    totalScore: 10,
    riskLevel: "LOW",
    confidence: 90,
    reasons: [],
  },
  {
    id: "linearSearch:41",
    kind: "method",
    name: "linearSearch",
    startLine: 41,
    endLine: 46,
    text: "for (...) { if (...) return i }",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
    timeScore: 18,
    spaceScore: 5,
    totalScore: 23,
    riskLevel: "MEDIUM",
    confidence: 80,
    reasons: [
      {
        type: "time",
        pattern: "single-loop",
        detail: "Single loop iterates through n elements",
        impact: "medium",
        confidence: 80,
        lineNumber: 41,
      },
    ],
  },
  {
    id: "binarySearch:23",
    kind: "method",
    name: "binarySearch",
    startLine: 23,
    endLine: 34,
    text: "while (left <= right) { ... }",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
    timeScore: 12,
    spaceScore: 5,
    totalScore: 17,
    riskLevel: "LOW",
    confidence: 85,
    reasons: [],
  },
  {
    id: "nestedLoop:69",
    kind: "method",
    name: "nestedLoop",
    startLine: 69,
    endLine: 79,
    text: "for (...) { for (...) {...} }",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1)",
    timeScore: 33,
    spaceScore: 5,
    totalScore: 38,
    riskLevel: "MEDIUM",
    confidence: 82,
    reasons: [
      {
        type: "time",
        pattern: "nested-loop-2",
        detail: "Two nested loops produce quadratic time",
        impact: "high",
        confidence: 85,
        lineNumber: 69,
      },
    ],
  },
  {
    id: "mergeSort:54",
    kind: "method",
    name: "mergeSort",
    startLine: 54,
    endLine: 62,
    text: "recursive split and merge",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
    timeScore: 25,
    spaceScore: 20,
    totalScore: 45,
    riskLevel: "MEDIUM",
    confidence: 75,
    reasons: [
      {
        type: "space",
        pattern: "array-copy",
        detail: "Temporary arrays created during merge",
        impact: "medium",
        confidence: 70,
        lineNumber: 54,
      },
    ],
  },
  {
    id: "fibonacci:104",
    kind: "method",
    name: "exponentialFibonacci",
    startLine: 104,
    endLine: 107,
    text: "return fib(n-1) + fib(n-2)",
    timeComplexity: "O(2^n)",
    spaceComplexity: "O(n)",
    timeScore: 45,
    spaceScore: 10,
    totalScore: 55,
    riskLevel: "HIGH",
    confidence: 90,
    reasons: [
      {
        type: "time",
        pattern: "recursive-branching",
        detail: "Exponential recursion growth",
        impact: "critical",
        confidence: 90,
        lineNumber: 104,
      },
    ],
  },
  // 4 more similar entries…
];
